### ISSUE TITLE
Copy url to clipboard doesn't work on Windows 10

### ISSUE THREAD

**Issue by slaFFik** [KELiON/cerebro-gif#1]
As it seems we don't have a `cmd` button to copy (obviously). 
`ctrl+c` doesn't work.

**Comment by KELiON** [comment]
@slaFFik exactly! I'll add support for copy by `ctrl+c` for everything (not only gif) in the [main](https://github.com/KELiON/cerebro) app in next release. Currently, you can copy URL to gif by selecting it (click it or select by enter)
