### ISSUE TITLE
gif not working

### ISSUE THREAD

**Issue by moeinrahimi** [KELiON/cerebro-gif#3]
hi
i just installed gif plugin and it's not working, sure when i type 'gif', find relevlant gif appears but it always goes for google search, when i type gif something the result is google searches.

**Comment by KELiON** [comment]
@moeinrahimi hello! can you attach a screenshot and your request?

**Comment by moeinrahimi** [comment]
![screenshot_2017-01-31_20-50-36](https://cloud.githubusercontent.com/assets/13715024/22476286/0adfb0de-e7f7-11e6-82d6-13fb99976aff.png)

**Comment by KELiON** [comment]
@moeinrahimi can you check console? 

1) Type settings and turn on developer mode, turn on "show in menu bar";
2) Toggle Cerebro window and from tray menu select development → dev tools (main), switch to `console` tab;
3) Reload everything (tray → development → reload);
4) Try to use gif plugin and check what do you have in console;

**Comment by moeinrahimi** [comment]
@KELiON I get 403 error, giphy server is block in my country, that's a shame .
thank you anyway.
