### ISSUE TITLE
Memoizing the results from giphy causes a lot of memory consumption

### ISSUE THREAD

**Issue by codingmatty** [KELiON/cerebro-gif#4]
I know that electron apps use a lot of memory to begin with, but I notice that Cerebro helpers use a lot, and I think this plugin may be the culprit. (I use it a lot).

I have been looking into the `memoizee` library, and notice that there is no default limit on size, nor a default limit on how long to hold things. There is also no way to store the results to disk instead of keeping them in memory. I believe all of this causes Cerebro's memory footprint to grow the more this plugin is used.

Short term, I'd suggest adding some size limits, and time limits.
Long term, I'd suggest looking into different memoize libraries to use that would allow developers to save results to disk instead of holding them in memory.

**Comment by KELiON** [comment]
@codingmatty I'd say that storing results on disk is not memoization, so we should split these two terms – memoization and caching. In this plugins we only memoize but I agree that we should add some TTL to memoized results.

**Comment by KELiON** [comment]
@codingmatty can you add this in PR? You just need to add options object to `memoize` call with `maxAge` key (like in [google plugin](https://github.com/KELiON/cerebro-google/blob/2def8c905903c254c8b722caa8dd25db32ee6abb/src/getSuggestions.js#L20))
